CowWeb_ver1/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.routers import DefaultRouter
from rest_framework.views import APIView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from apps.WebCloud.views import choose_province, choose_city, choose_district
from apps.users.views import UserViewSet

router = DefaultRouter()
router.register("", UserViewSet)
# swagger文档
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


class SimplePostView(APIView):
    def post(self, request, *args, **kwargs):
        data = request.data  # 获取POST数据
        # 在这里处理数据，例如：

        # 返回响应
        return Response({"data": data})

    def get(self, request, *args, **kwargs):
        data = request.query_params  # 获取POST数据
        # 在这里处理数据，例如：

        # 返回响应
        return Response({"data": data})


urlpatterns = [
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("admin/", admin.site.urls),
    path(
        "api/",
        include(
            [
                path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
                path(
                    "token/refresh/", TokenRefreshView.as_view(), name="token_refresh"
                ),
                path("users/", include("apps.users.urls")),
                path("", include("apps.WebCloud.urls")),
                path("health-cards/", SimplePostView.as_view(), name="health_card"),
                # 省/市/区域联动
                path("province/", choose_province),
                path("city/", choose_city),
                path("district/", choose_district),
            ]
        ),
    ),
]

apps/WebCloud/urls.py
from rest_framework.routers import DefaultRouter

from apps.WebCloud import views

router = DefaultRouter()
router.register("auto-history", views.AutoHistoryDataViewSet)
router.register("ration-history", views.RationHistoryDataViewSet)
router.register("cages", views.CageViewSet)
router.register("rfids", views.RFIDViewSet)
router.register("feeding-standards", views.FeedingStandardViewSet)
router.register("calves", views.CalfViewSet)
router.register("remaining-milks", views.RemainingMilkViewSet)
router.register("rfid-cages", views.RFIDCageViewSet)
router.register("calf-cages", views.CalfCageViewSet)
router.register("data-update-status", views.DataUpdateStatusViewSet)
router.register("device-logs", views.DeviceLogViewSet)
router.register("pastures", views.PastureViewSet)
router.register("unlink-calves", views.UnlinkCalfViewSet)
urlpatterns = router.get_urls()

apps/WebCloud/models.py
from datetime import date, timedelta, datetime
from typing import Optional

# from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Model
from rest_framework.exceptions import ValidationError


class BaseModel(models.Model):
    """
    基类，公共字段
    """

    c_time = models.DateTimeField("创建时间", auto_now_add=True, db_index=True)
    u_time = models.DateTimeField("更新时间", auto_now=True, db_index=True)
    is_delete = models.BooleanField("逻辑删除", default=False, db_index=True)

    class Meta:
        # 抽象类，用于继承，迁移时不会创建
        abstract = True


class Pasture(BaseModel):
    """
    牧场类
    """

    name = models.CharField("牧场", max_length=100, unique=True)
    province = models.CharField(verbose_name="省份", max_length=25, db_index=True)
    city = models.CharField(verbose_name="城市", max_length=25, db_index=True)
    district = models.CharField(verbose_name="区/县", max_length=25, db_index=True)
    address_detail = models.TextField(
        verbose_name="详细地址", max_length=500, default="", blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        db_table = "pasture"  # 表名
        verbose_name = "牧场"  # 站点显示名
        verbose_name_plural = verbose_name


class RFID(models.Model):
    """
    RFID 类
    """

    rfid_id = models.CharField("RFID卡号", max_length=40, unique=True)
    is_invalid = models.BooleanField("已作废", default=False, db_index=True)
    pasture = models.ForeignKey(
        Pasture, verbose_name="牧场", on_delete=models.CASCADE, related_name="rfids"
    )

    def __str__(self):
        return self.rfid_id

    @property
    def is_bound(self) -> bool:
        """
        是否已绑定
        """
        return RFIDCage.check_bound(self)

    def unbind(self):
        """
        解绑
        """
        return RFIDCage.unbind(self)

    def check_useful(self):
        """
        检查是否可用
        """
        if self.is_bound:
            raise ValidationError("该RFID卡已经绑定了笼子!")
        if self.is_invalid:
            raise ValidationError("该RFID卡已经废弃!")

    def bound_cage(self, cage):
        """
        与犊牛笼绑定
        """
        self.check_useful()
        if cage.is_bound:
            raise ValidationError(f"犊牛笼({cage.cage_id})已经绑定RFID卡了!")

        RFIDCage.objects.create(rfid=self, cage=cage)

    @property
    def cage(self):
        """
        获取RFID绑定的犊牛笼
        """
        if not self.is_bound:
            raise ValidationError("该RFID卡未绑定笼子!")
        return self.rfid_cage.cage

    @property
    def calf(self):
        """
        获取RFID绑定的犊牛笼的犊牛
        """
        if not self.is_bound:
            raise ValidationError("该RFID卡未绑定笼子!")
        cage = self.rfid_cage.cage
        return cage.calf

    @property
    def feeding_standard(self):
        """
        获取RFID绑定的犊牛笼的犊牛的喂养标准
        """
        return self.calf.feeding_standard

    @property
    def ration_history_data(self):
        """
        ration历史数据
        """
        return RationHistoryData.objects.filter(rfid_id=self.rfid_id).first()

    @property
    def auto_history_data(self):
        """
        auto历史数据
        """
        return AutoHistoryData.objects.filter(rfid_id=self.rfid_id).first()

    class Meta:
        db_table = "rfid"  # 表名
        verbose_name = "RFID"  # 站点显示名
        verbose_name_plural = verbose_name


class Cage(models.Model):
    """
    犊牛笼类
    """

    # Cage_RFID = models.OneToOneField(RFID, on_delete=models.SET_DEFAULT, default=9999, help_text='RFID卡号')

    cage_id = models.CharField("笼号编码", max_length=40, unique=True)
    area = models.CharField(
        "区域", max_length=10, null=True, blank=True, default="", db_index=True
    )
    area_id = models.CharField(
        "区号", max_length=10, null=True, blank=True, default="", db_index=True
    )
    descr = models.CharField("备注", max_length=1000, null=True, blank=True, default="")
    pasture = models.ForeignKey(
        Pasture, verbose_name="牧场", on_delete=models.CASCADE, related_name="cages"
    )

    def __str__(self):
        return self.cage_id

    @property
    def is_bound(self) -> bool:
        """
        是否已绑定
        """
        return RFIDCage.check_bound(cage=self)

    @property
    def rfid(self):
        if not self.is_bound:
            return None
        return self.rfid_cage.rfid

    @property
    def feeding_standard(self):
        return self.rfid.feeding_standard

    @property
    def auto_history_data(self):
        return self.rfid.auto_history_data

    @property
    def ration_history_data(self):
        return self.rfid.ration_history_data

    def has_calf(self) -> bool:
        """
        是否有犊牛了
        """
        return CalfCage.check_bound(cage=self)

    @property
    def bound_time(self):
        return self.rfid_cage.bound_time

    @property
    def has_calf_time(self):
        return self.calf_cage.cage_entry_time

    @property
    def calf(self):
        """
        笼中的犊牛
        """
        if not self.has_calf():
            raise ValidationError("该犊牛笼没有牛!")
        return self.calf_cage.calf

    def bound_rfid(self, rfid):
        """
        与RFID卡绑定
        """
        rfid.check_useful()
        if self.is_bound:
            raise ValidationError("该笼子已经绑定RFID卡了!")

        RFIDCage.objects.create(rfid=rfid, cage=self)

    def put_calf(self, calf):
        if not self.is_bound:
            raise ValidationError("该笼子还未绑定RFID卡!")
        if self.has_calf():
            raise ValidationError("该笼子已经有犊牛了!")
        if calf.is_in_cage:
            raise ValidationError(f"犊牛({calf.calf_id})已经入过笼了!")
        CalfCage.objects.create(calf=calf, cage=self)

    class Meta:
        db_table = "cage"  # 表名
        verbose_name = "犊牛笼"  # 站点显示名
        verbose_name_plural = verbose_name


class RFIDCage(models.Model):
    rfid = models.OneToOneField(
        RFID,
        verbose_name="RFID",
        on_delete=models.CASCADE,
        related_name="rfid_cage",
        unique=True,
    )
    cage = models.OneToOneField(
        Cage,
        verbose_name="犊牛笼",
        on_delete=models.CASCADE,
        related_name="rfid_cage",
        unique=True,
    )
    bound_time = models.DateField("绑定时间", auto_now_add=True, db_index=True)

    def __str__(self):
        return f"{self.rfid.rfid_id}-{self.cage.cage_id}"

    @classmethod
    def unbind(cls, rfid=None, cage=None):
        if rfid:
            cls.objects.filter(rfid=rfid).first().delete()
        elif cage:
            cls.objects.filter(cage=rfid).first().delete()
        return True

    @classmethod
    def bound(cls, rfid: RFID, cage: Cage):
        """
        绑定RFID卡与犊牛笼
        """
        if not (
            cls.objects.filter(rfid=rfid).exists()
            and cls.objects.filter(cage=cage).exists()
        ):
            cls.objects.create(rfid=rfid, cage=cage)

    @classmethod
    def check_bound(
        cls, rfid: Optional[RFID] = None, cage: Optional[Cage] = None
    ) -> bool:
        if rfid:
            return cls.objects.filter(rfid=rfid).exists()
        if cage:
            return cls.objects.filter(cage=cage).exists()

    class Meta:
        db_table = "rfid_cage"  # 表名
        verbose_name = "RFID & 犊牛笼"  # 站点显示名
        verbose_name_plural = verbose_name


class Calf(models.Model):
    """
    犊牛
    """

    SEXES = ((1, "公"), (2, "母"))
    calf_id = models.CharField("犊牛耳标ID", max_length=40, unique=True)
    date_of_birth = models.DateField("出生日期", db_index=True)
    sex = models.SmallIntegerField("性别", choices=SEXES, default=2, db_index=True)
    weight_day_add = models.FloatField("日增重", default=1.0, db_index=True)
    birth_weight = models.FloatField("出生体重(kg)", default=0.0, db_index=True)
    # Age_in_days = models.IntegerField('日龄', default=1, help_text='日龄')
    adjusted_feeding = models.FloatField("临时调整饲喂量", default=0.0, db_index=True)
    descr = models.CharField("备注", max_length=1000, null=True, blank=True, default="")
    pasture = models.ForeignKey(
        Pasture, verbose_name="牧场", on_delete=models.CASCADE, related_name="calves"
    )

    def __str__(self):
        return self.calf_id

    @property
    def cage(self):
        if not self.is_in_cage:
            return None
        return self.calf_cage.cage

    @property
    def rfid(self):
        return self.cage.rfid

    @property
    def is_in_cage(self) -> bool:
        """
        是否入笼
        """
        return CalfCage.check_bound(self)

    @classmethod
    def filter_is_in_cage(cls):
        return cls.objects.filter(calf_cage__isnull=False)

    @classmethod
    def filter_not_in_cage(cls):
        return cls.objects.filter(calf_cage__isnull=True)

    @property
    def in_cage_time(self):
        """
        入笼时间
        """
        return self.calf_cage.cage_entry_time

    @property
    def cage_entry_time(self):
        """
        入笼时间
        """
        if self.is_in_cage:
            return self.calf_cage.cage_entry_time

    def enter_cage(self, cage):
        """
        入笼
        """
        if self.is_in_cage:
            raise ValidationError("该犊牛已经在笼子里了!")
        if cage.has_calf():
            raise ValidationError(f"笼子({cage.cage_id})已经有犊牛了!")
        CalfCage.objects.create(cage=cage, calf=self)

    @property
    def feeding_standard(self):
        """
        饲养标准
        """
        return FeedingStandard.get_calf_standard(self)

    @property
    def age_in_days(self) -> int:
        """
        日龄
        """
        return (date.today() - self.date_of_birth).days

    @property
    def auto_history_data(self):
        return self.rfid.auto_history_data

    @property
    def history_data(self):
        return self.rfid.ration_history_data

    class Meta:
        db_table = "calf"  # 表名
        verbose_name = "犊牛"  # 站点显示名
        verbose_name_plural = verbose_name


class CalfCage(models.Model):
    calf = models.OneToOneField(
        Calf,
        verbose_name="犊牛",
        on_delete=models.CASCADE,
        related_name="calf_cage",

apps/WebCloud/templates/area.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify simpletags %}

{% block extrahead %}{{ block.super }}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    {{ media }}

{% endblock %}
{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}"/>{% endblock %}
{% block content %}
    <style type="text/css">
        .inline-group .tabular td.original p {
            margin-top: -33px;
        }

        .page-header {
            padding: 10px;
        }

    </style>
    <div id="content-main" class="form-main">
        <a href="http://api.map.baidu.com/lbsapi/getpoint/index.html" target="_blank"
           style="float: right">百度地图坐标拾取器</a>
        <div class="page-header">
            <el-page-header @back="goBack" content="{{ title }}"/>

        </div>
        {% block object-tools %}
            {% if change %}{% if not is_popup %}
                <ul class="object-tools">
                    {% block object-tools-items %}
                        <li>
                            <el-dialog title="{% trans "History" %}" :visible.sync="dialogTableVisible">
                                <iframe frameborder="0" :src="url" width="100%" height="300"></iframe>
                            </el-dialog>
                            {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}

                            <el-button @click="go_url('{% add_preserved_filters history_url %}')" class="historylink"
                                       icon="fas fa-history">{% trans "History" %}</el-button>
                        </li>
                        {% if has_absolute_url %}
                            <li>
                                <el-button @click="window.open('{{ absolute_url }}')" class="viewsitelink"
                                           icon="fas fa-globe-asia">{% trans "View on site" %}</el-button>
                            </li>
                        {% endif %}
                    {% endblock %}
                </ul>
            {% endif %}{% endif %}
        {% endblock %}
        <form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post"
              id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
            <div>
                {% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1"/>{% endif %}
                {% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}"/>{% endif %}
                {% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
                {% if errors %}
                    <div id="alert">
                        <el-alert
                                title="{% if errors|length == 1 %}
                            {% trans "Please correct the error below." %}
                        {% else %}
                            {% trans "Please correct the errors below." %}
                        {% endif %}"
                                type="error">
                        </el-alert>
                    </div>
                    {{ adminform.form.non_field_errors }}
                {% endif %}

                {% block field_sets %}
                    {% for fieldset in adminform %}
                        {% include "admin/includes/fieldset.html" %}
                    {% endfor %}
                {% endblock %}

                {% block after_field_sets %}{% endblock %}

                {% block inline_field_sets %}
                    {% for inline_admin_formset in inline_admin_formsets %}
                        {% include inline_admin_formset.opts.template %}
                    {% endfor %}
                {% endblock %}

                {% block after_related_objects %}{% endblock %}

                {% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

                {% block admin_change_form_document_ready %}
                    <script type="text/javascript"
                            id="django-admin-form-add-constants"
                            src="{% static 'admin/js/change_form.js' %}"
                            {% if adminform and add %}
                            data-model-name="{{ opts.model_name }}"
                            {% endif %}>
                    </script>
                    <script type="text/javascript">
                        (function ($) {
                            $('#id_city').change(function () {
                                let p_id = $('#id_province').val();
                                let c_id = $('#id_city').val();
                                $.get('/api/district/', {"p": p_id, "c": c_id}, function (a_info) {
                                    var area_info = $('#id_district').empty().append('<option value>' + '---------' + '</option>');
                                    $.each(a_info, function (i, area) {
                                        area_info.append('<option value="' + area + '">' + area + '</option>')
                                    });
                                    {% if change %}
                                        $("#id_district").find("option:contains({{ original.district }})").attr('selected', true);
                                    {% endif %}
                                });
                            });

                            $('#id_province').change(function () {
                                let p_id = $('#id_province').val();
                                $.get('/api/city/', {'p': p_id}, function (c_info) {
                                    var city_info = $('#id_city').empty().append('<option value>' + '---------' + '</option>');
                                    $.each(c_info, function (i, city) {
                                        city_info.append('<option value="' + city + '">' + city + '</option>')
                                    });
                                    {% if change %}
                                        $("#id_city").find("option:contains({{ original.city }})").attr('selected', true);
                                        $("#id_city").trigger("change");
                                    {% endif %}
                                });
                            });

                            $.get('/api/province/', function (p_info) {
                                var province_info = $('#id_province').empty().append('<option value>' + '---------' + '</option>');
                                $.each(p_info, function (i, province) {
                                    province_info.append('<option value="' + province + '">' + province + '</option>')
                                });
                                {% if change %}
                                    $("#id_province").find("option:contains({{ original.province }})").attr('selected', true);
                                    $("#id_province").trigger("change");
                                {% endif %}

                                $('#id_province').val("北京市")
                                $('#id_province').change()
                                $('#id_city').val("深圳市")

                            });


                        })(django.jQuery);


                    </script>

                {% endblock %}

                {# JavaScript for prepopulated fields #}
                {% prepopulated_fields_js %}

            </div>
        </form>

    </div>
    <script type="text/javascript">
        new Vue({
            el: '.page-header',
            methods: {
                goBack: function () {
                    window.location.href = '{% get_model_url %}'
                }
            }
        })
        if ($(".object-tools").length != 0) {
            new Vue({
                el: '.object-tools',
                data: {
                    dialogTableVisible: false,
                    url: ''
                },
                methods: {
                    go_url: function (url) {
                        this.url = url;
                        this.dialogTableVisible = true;
                    }
                }
            })
        }
        if (document.getElementById('alert')) {
            new Vue({
                el: '#alert'
            })
        }
    </script>
{% endblock %}